"""
emulator/scenarios/base.py — Abstract base class for emulator scenarios

Each scenario runs in its own daemon thread and calls a user-supplied
callback for every generated line.  Subclasses only need to implement
_generate(); all threading and timing is handled here.

Subclass contract:
    def _generate(self) -> Iterator[tuple[bytes, float]]:
        yield b"line\\r\\n", delay_seconds
        yield b"next\\r\\n", delay_seconds

The base class feeds each (data, delay) pair to the callback, sleeping
between pairs via Event.wait() so that stop() is always responsive.
"""
from __future__ import annotations

import threading
from collections.abc import Callable, Iterator


class BaseScenario:
    """
    Thread-based scenario runner.

    Args:
        callback:  Called with each generated bytes line.
                   Typically VirtualPort.write, but can be any sink.
        loop:      If True (default), _generate() restarts automatically
                   after it is exhausted.  If False, the thread exits after
                   one full pass through the generator.
    """

    def __init__(
        self,
        callback: Callable[[bytes], None],
        *,
        loop: bool = True,
    ) -> None:
        self._callback = callback
        self._loop = loop
        self._stop_event = threading.Event()
        self._thread: threading.Thread | None = None

    # ── Control ───────────────────────────────────────────────────────────────

    def start(self) -> None:
        """Spawn the scenario thread.  No-op if already running."""
        if self.is_running:
            return
        self._stop_event.clear()
        self._thread = threading.Thread(
            target=self._run,
            daemon=True,
            name=f"Scenario-{self.name}",
        )
        self._thread.start()

    def stop(self, timeout: float = 2.0) -> None:
        """
        Signal the thread to stop and wait for it to exit.
        Returns after at most `timeout` seconds even if the thread is stuck.
        """
        self._stop_event.set()
        if self._thread is not None:
            self._thread.join(timeout)
            self._thread = None

    # ── Properties ────────────────────────────────────────────────────────────

    @property
    def is_running(self) -> bool:
        return self._thread is not None and self._thread.is_alive()

    @property
    def name(self) -> str:
        """Human-readable name derived from the concrete class."""
        return type(self).__name__

    # ── Context manager ───────────────────────────────────────────────────────

    def __enter__(self) -> BaseScenario:
        self.start()
        return self

    def __exit__(self, *_) -> None:
        self.stop()

    # ── Subclass interface ────────────────────────────────────────────────────

    def _generate(self) -> Iterator[tuple[bytes, float]]:
        """
        Yield (line, delay_seconds) pairs that represent one full scenario
        pass.  The base class calls the callback and sleeps between pairs.

        Must be overridden by every concrete scenario.
        """
        raise NotImplementedError(f"{self.name}._generate() not implemented")

    # ── Internal ──────────────────────────────────────────────────────────────

    def _run(self) -> None:
        """
        Main thread loop.

        Drives _generate() and sleeps between lines using Event.wait() so
        that a stop() call always interrupts the current delay immediately.
        """
        while not self._stop_event.is_set():
            for data, delay in self._generate():
                if self._stop_event.is_set():
                    return
                self._callback(data)
                # Interruptible sleep: returns early when stop() is called
                self._stop_event.wait(delay)

            if not self._loop:
                break
